import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <script dangerouslySetInnerHTML={{ __html: `
          // Log scroll resets and RSC fetches to help diagnose the bug
          (function() {
            var htmlProto = Object.getOwnPropertyDescriptor(Element.prototype, 'scrollTop');
            var origFetch = window.fetch;
            Object.defineProperty(document.documentElement, 'scrollTop', {
              get: function() { return htmlProto.get.call(this); },
              set: function(v) {
                if (v === 0 && window.scrollY > 50)
                  console.log('[scroll-debug] scrollTop=0 from scrollY=' + window.scrollY);
                return htmlProto.set.call(this, v);
              },
              configurable: true
            });
            window.fetch = function(input) {
              var url = typeof input === 'string' ? input : (input instanceof Request ? input.url : '');
              if (url.indexOf('_rsc') !== -1)
                console.log('[scroll-debug] RSC fetch:', url.substring(0, 120));
              return origFetch.apply(this, arguments);
            };
          })();
        `}} />
        {children}
      </body>
    </html>
  );
}
